// <auto-generated />
using System;
using BlackSlope.Repositories.Movies.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlackSlope.Repositories.Movies.Migrations
{
    [DbContext(typeof(MovieContext))]
    [Migration("20190812225245_seed-data")]
    partial class seeddata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BlackSlope.Repositories.Movies.DtoModels.MovieDtoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<DateTime?>("ReleaseDate");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .HasName("IX_Movies_Title");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
                            Title = "The Shawshank Redemption"
                        },
                        new
                        {
                            Id = 2,
                            Description = "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
                            Title = "The Godfather"
                        },
                        new
                        {
                            Id = 3,
                            Description = "When the menace known as The Joker emerges from his mysterious past, he wreaks havoc and chaos on the people of Gotham.",
                            Title = "The Dark Knight"
                        },
                        new
                        {
                            Id = 4,
                            Description = "The early life and career of Vito Corleone in 1920s New York City is portrayed, while his son, Michael, expands and tightens his grip on the family crime syndicate.",
                            Title = "The Godfather: Part II"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.",
                            Title = "The Lord of the Rings: The Return of the King"
                        },
                        new
                        {
                            Id = 6,
                            Description = "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
                            Title = "Pulp Fiction"
                        },
                        new
                        {
                            Id = 7,
                            Description = "In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.",
                            Title = "Schindler's List"
                        },
                        new
                        {
                            Id = 8,
                            Description = "A jury holdout attempts to prevent a miscarriage of justice by forcing his colleagues to reconsider the evidence.",
                            Title = "12 Angry Men"
                        },
                        new
                        {
                            Id = 9,
                            Description = "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
                            Title = "Inception"
                        },
                        new
                        {
                            Id = 10,
                            Description = "An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into something much, much more.",
                            Title = "Fight Club"
                        },
                        new
                        {
                            Id = 11,
                            Description = "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.",
                            Title = "The Lord of the Rings: The Fellowship of the Ring"
                        },
                        new
                        {
                            Id = 12,
                            Description = "The presidencies of Kennedy and Johnson, the events of Vietnam, Watergate, and other history unfold through the perspective of an Alabama man with an IQ of 75.",
                            Title = "Forrest Gump"
                        },
                        new
                        {
                            Id = 13,
                            Description = "A bounty hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold buried in a remote cemetery.",
                            Title = "The Good, the Bad and the Ugly"
                        },
                        new
                        {
                            Id = 14,
                            Description = "After the devastating events of Avengers: Infinity War (2018), the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.",
                            Title = "Avengers: Endgame"
                        },
                        new
                        {
                            Id = 15,
                            Description = "While Frodo and Sam edge closer to Mordor with the help of the shifty Gollum, the divided fellowship makes a stand against Sauron's new ally, Saruman, and his hordes of Isengard.",
                            Title = "The Lord of the Rings: The Two Towers"
                        },
                        new
                        {
                            Id = 16,
                            Description = "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
                            Title = "The Matrix"
                        },
                        new
                        {
                            Id = 17,
                            Description = "The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners Jimmy Conway and Tommy DeVito in the Italian-American crime syndicate.",
                            Title = "Goodfellas"
                        },
                        new
                        {
                            Id = 18,
                            Description = "After the Rebels are brutally overpowered by the Empire on the ice planet Hoth, Luke Skywalker begins Jedi training with Yoda, while his friends are pursued by Darth Vader.",
                            Title = "Star Wars: Episode V - The Empire Strikes Back"
                        },
                        new
                        {
                            Id = 19,
                            Description = "A criminal pleads insanity after getting into trouble again and once in the mental institution rebels against the oppressive nurse and rallies up the scared patients.",
                            Title = "One Flew Over the Cuckoo's Nest"
                        },
                        new
                        {
                            Id = 20,
                            Description = "A poor village under attack by bandits recruits seven unemployed samurai to help them defend themselves.",
                            Title = "Seven Samurai"
                        },
                        new
                        {
                            Id = 21,
                            Description = "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
                            Title = "Interstellar"
                        },
                        new
                        {
                            Id = 22,
                            Description = "In the slums of Rio, two kids' paths diverge as one struggles to become a photographer and the other a kingpin.",
                            Title = "City of God"
                        },
                        new
                        {
                            Id = 23,
                            Description = "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and where humans are changed into beasts.",
                            Title = "Spirited Away"
                        },
                        new
                        {
                            Id = 24,
                            Description = "Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed in action.",
                            Title = "Saving Private Ryan"
                        },
                        new
                        {
                            Id = 25,
                            Description = "The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape, yet who has a mysterious gift.",
                            Title = "The Green Mile"
                        },
                        new
                        {
                            Id = 26,
                            Description = "When an open-minded Jewish librarian and his son become victims of the Holocaust, he uses a perfect mixture of will, humor, and imagination to protect his son from the dangers around their camp.",
                            Title = "Life Is Beautiful "
                        },
                        new
                        {
                            Id = 27,
                            Description = "A sole survivor tells of the twisty events leading up to a horrific gun battle on a boat, which began when five criminals met at a seemingly random police lineup.",
                            Title = "The Usual Suspects"
                        },
                        new
                        {
                            Id = 28,
                            Description = "Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.",
                            Title = "Se7en"
                        },
                        new
                        {
                            Id = 29,
                            Description = "Mathilda, a 12-year-old girl, is reluctantly taken in by Léon, a professional assassin, after her family is murdered.",
                            Title = "Léon: The Professional"
                        },
                        new
                        {
                            Id = 30,
                            Description = "A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer, a madman who skins his victims.",
                            Title = "The Silence of the Lambs"
                        },
                        new
                        {
                            Id = 31,
                            Description = "Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee and two droids to save the galaxy from the Empire's world-destroying battle station, while also attempting to rescue Princess Leia from the mysterious Darth Vader.",
                            Title = "Star Wars: Episode IV - A New Hope"
                        },
                        new
                        {
                            Id = 32,
                            Description = "An angel is sent from Heaven to help a desperately frustrated businessman by showing him what life would have been like if he had never existed.",
                            Title = "It's a Wonderful Life"
                        },
                        new
                        {
                            Id = 33,
                            Description = "A faded television actor and his stunt double strive to achieve fame and success in the film industry during the final years of Hollywood's Golden Age in 1969 Los Angeles.",
                            Title = "Once Upon a Time ... in Hollywood"
                        },
                        new
                        {
                            Id = 34,
                            Description = "Teen Miles Morales becomes Spider-Man of his reality, crossing his path with five counterparts from other dimensions to stop a threat for all realities.",
                            Title = "Spider-Man: Into the Spider-Verse"
                        },
                        new
                        {
                            Id = 35,
                            Description = "The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation and ruin puts an end to the universe.",
                            Title = "Avengers: Infinity War"
                        },
                        new
                        {
                            Id = 36,
                            Description = "A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a student's potential.",
                            Title = "Whiplash"
                        },
                        new
                        {
                            Id = 37,
                            Description = "After he becomes a quadriplegic from a paragliding accident, an aristocrat hires a young man from the projects to be his caregiver.",
                            Title = "The Intouchables"
                        },
                        new
                        {
                            Id = 38,
                            Description = "After a tragic accident, two stage magicians engage in a battle to create the ultimate illusion while sacrificing everything they have to outwit each other.",
                            Title = "The Prestige"
                        },
                        new
                        {
                            Id = 39,
                            Description = "An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston.",
                            Title = "The Departed"
                        },
                        new
                        {
                            Id = 40,
                            Description = "A Polish Jewish musician struggles to survive the destruction of the Warsaw ghetto of World War II.",
                            Title = "The Pianist"
                        },
                        new
                        {
                            Id = 41,
                            Description = "A man with short-term memory loss attempts to track down his wife's murderer.",
                            Title = "Memento"
                        },
                        new
                        {
                            Id = 42,
                            Description = "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.",
                            Title = "Gladiator"
                        },
                        new
                        {
                            Id = 43,
                            Description = "A former neo-nazi skinhead tries to prevent his younger brother from going down the same wrong path that he did.",
                            Title = "American History X"
                        },
                        new
                        {
                            Id = 44,
                            Description = "A Lion cub crown prince is tricked by a treacherous uncle into thinking he caused his father's death and flees into exile in despair, only to learn in adulthood his identity and his responsibilities.",
                            Title = "The Lion King"
                        },
                        new
                        {
                            Id = 45,
                            Description = "A cyborg, identical to the one who failed to kill Sarah Connor, must now protect her teenage son, John Connor, from a more advanced and powerful cyborg.",
                            Title = "Terminator 2: Judgment Day"
                        },
                        new
                        {
                            Id = 46,
                            Description = "A filmmaker recalls his childhood when falling in love with the pictures at the cinema of his home village and forms a deep friendship with the cinema's projectionist.",
                            Title = "Cinema Paradiso"
                        },
                        new
                        {
                            Id = 47,
                            Description = "A young boy and his little sister struggle to survive in Japan during World War II.",
                            Title = "Grave of the Fireflies"
                        },
                        new
                        {
                            Id = 48,
                            Description = "Marty McFly, a 17-year-old high school student, is accidentally sent thirty years into the past in a time-traveling DeLorean invented by his close friend, the maverick scientist Doc Brown.",
                            Title = "Back to the Future"
                        },
                        new
                        {
                            Id = 49,
                            Description = "In 1936, archaeologist and adventurer Indiana Jones is hired by the U.S. government to find the Ark of the Covenant before Adolf Hitler's Nazis can obtain its awesome powers.",
                            Title = "Raiders of the Lost Ark"
                        },
                        new
                        {
                            Id = 50,
                            Description = "A U.S. Army officer serving in Vietnam is tasked with assassinating a renegade Special Forces Colonel who sees himself as a god.",
                            Title = "Apocalypse Now"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
