version: '3.5'
services: 
  db: 
    container_name: db
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Developer    
    ports: 
      - "1401:1433"
  apiapp:
    container_name: apiapp
    image: blackslope/api-app
    build: 
      context: .
    depends_on:
      - db
    ports: 
      - "5010:80"
    environment:
      ASPNETCORE_ENVIRONMENT: "docker"
  # TODO: Figure out why Docker won't build on my machine
  # identityserver:
  #   container_name: identityserver
  #   image: blackslope/identity-server
  #   build: 
  #     context: ./BlackSlope.IdentityProvider
  #   depends_on:
  #     - apiapp
  #   ports: 
  #     - "5020:80"
  #   environment:
  #     ASPNETCORE_ENVIRONMENT: "docker"
  #     TENANT_ID: "api1"
  #     HOST_NAME: "http://localhost:5000"
    